-- Criação da tabela PROFESSOR baseada na model Java
CREATE TABLE PROFESSOR (
    ID           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(150) NOT NULL,
    DEPARTAMENTO VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(150) NOT NULL,
    TITULACAO    VARCHAR2(80)
);

-- Regra de unicidade de e-mail
CREATE UNIQUE INDEX UK_PROFESSOR_EMAIL ON PROFESSOR(EMAIL);

-- **Observação**: em Oracle, `IDENTITY` funciona em versões 12c+;
-- se não disponível no ambiente, substitua por `SEQUENCE + trigger`.